name: expert_system
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  fl_chart: ^0.61.0
  percent_indicator: ^4.2.3
  bitsdojo_window: ^0.1.5
  menu_bar: ^0.4.1
  another_flushbar: ^1.12.29
  file_picker: ^5.2.6
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/Psychologist-amico.png
